name: msdesis
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - torchvision=0.8.1
  - cudatoolkit=10.1.243
  - pytorch=1.7.0
  - opencv=4.5.5
  - tqdm
  - monai=0.8.0
  - kornia=0.5.5
  - wandb
  - pandas
